### ISSUE TITLE
MapData class fields are empty for custom maps

### ISSUE THREAD

**Issue by cormac-doyle** [Shiqan/FortniteReplayDecompressor#54]
When parsing replay files on custom maps, the fields WorldGridTotalSize, WorldGridSpacing, WorldGridEnd, and WorldGridStart are empty

**Comment by cormac-doyle** [comment]
Example file:
[custom.replay.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/14516455/custom.replay.zip)

**Comment by Shiqan** [comment]
The default `ParseMode` required for MapData is `ParseMode.Full`: https://github.com/Shiqan/FortniteReplayDecompressor/blob/c322d58dd0424f6bdbd33bf11812554a2a9f04f7/src/FortniteReplayReader/Models/NetFieldExports/FortPoiManager.cs#L8

So you can either run the parser with ParseMode.Full or change this line to ParseMode.Minimal.

Now that this export group is being parsed, it turns out that it has only 2 exports for the replay you provided.
- `WorldGridSpacing` 
- `PoiTagContainerTableSize`

The `PoiTagContainerTableSize`is successfully parsed, and is 0.
The `WorldGridSpacing` has 128 bits but it only parsed 64 bits, seems like it changed from a 64 bit vector to 128 bits at some point.
Looking at the bits, it is a grid of (4, 4).

Hope this helps 😄
